import { article as behavioural_models_in_sport_and_education__understanding_and_utilising_individual_differences } from "./behavioural-models-in-sport-and-education--understanding-and-utilising-individual-differences";

const articles = {
    [behavioural_models_in_sport_and_education__understanding_and_utilising_individual_differences.slug]: behavioural_models_in_sport_and_education__understanding_and_utilising_individual_differences
}